// Generated by seleniumbase-rs recorder
use seleniumbase_rs::{BaseCase, BrowserConfig};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut sb = BaseCase::new(BrowserConfig::default()).await?;
    sb.open("https://github.com").await?;
    sb.human_type("input[name='q']", "Rustlang").await?;
    sb.human_click("button[type='submit']").await?;
    sb.quit().await?;
    Ok(())
}
