use crate::BaseCase;
use crate::BrowserConfig;
use crate::SeleniumBaseError;
use std::io::{self, Write};
use std::path::PathBuf;

const STARTER_TEMPLATE: &str = r#"// SeleniumBase Rust recording template
// Generated by `sbase mkrec`
// Record actions here, or run an interactive recording session.
use seleniumbase_rs::{BaseCase, BrowserConfig};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut sb = BaseCase::new(BrowserConfig::default()).await?;
    sb.open("https://example.com").await?;
    // Add recorded actions here...
    sb.quit().await?;
    Ok(())
}
"#;

/// Writes a starter recording template to `file`.
pub fn make_recorder_file(file: &str) -> std::io::Result<PathBuf> {
    let path = PathBuf::from(file);
    std::fs::write(&path, STARTER_TEMPLATE)?;
    Ok(path)
}

/// Runs a simple stdin-based recorder without a live browser.
pub fn start_recorder() {
    println!("Starting SeleniumBase action recorder...");
    println!("Type actions as: click <selector>");
    println!("Type 'save <filename>' to export, or 'quit' to exit.");

    let mut recorder = crate::api::recorder::ActionRecorder::default();
    loop {
        print!("> ");
        let _ = io::stdout().flush();
        let mut input = String::new();
        if io::stdin().read_line(&mut input).is_err() {
            break;
        }
        let input = input.trim();
        if input.eq_ignore_ascii_case("quit") {
            break;
        }
        if let Some(path) = input.strip_prefix("save ") {
            let script = recorder.to_rust_script();
            match std::fs::write(path, script) {
                Ok(_) => println!("Saved recorded test to {}", path),
                Err(e) => eprintln!("Failed to save: {}", e),
            }
            break;
        }
        let parts: Vec<&str> = input.splitn(3, ' ').collect();
        if parts.len() >= 2 {
            let action = parts[0];
            let target = parts[1];
            let value = parts.get(2).copied();
            recorder.record(action, Some(target), value);
            println!("Recorded: {} {}", action, target);
        }
    }
}

/// Launches a live `BaseCase` session on `url` and records actions from an
/// interactive prompt.
///
/// Supported commands:
/// - `open <url>`
/// - `click <css>`
/// - `type <css> <text>`
/// - `assert_text <css> <text>`
/// - `save <file>`
/// - `quit`
pub async fn record_live_session(url: &str) -> Result<(), SeleniumBaseError> {
    let mut sb = BaseCase::new(BrowserConfig::default()).await?;
    sb.open(url).await?;

    println!("Live recording session started at {}", url);
    println!("Commands: open <url>, click <css>, type <css> <text>, assert_text <css> <text>, save <file>, quit");

    loop {
        print!("> ");
        let _ = io::stdout().flush();
        let mut input = String::new();
        if io::stdin().read_line(&mut input).is_err() {
            break;
        }
        let trimmed = input.trim();
        if trimmed.eq_ignore_ascii_case("quit") {
            break;
        }

        if let Err(e) = handle_live_command(&mut sb, trimmed).await {
            eprintln!("Error: {}", e);
        }
    }

    sb.quit().await?;
    println!("Live recording session ended.");
    Ok(())
}

async fn handle_live_command(sb: &mut BaseCase, input: &str) -> Result<(), SeleniumBaseError> {
    if let Some(rest) = input.strip_prefix("open ") {
        let url = rest.trim();
        sb.open(url).await?;
        println!("Opened {}", url);
        return Ok(());
    }
    if let Some(rest) = input.strip_prefix("click ") {
        let css = rest.trim();
        sb.click(css).await?;
        println!("Clicked {}", css);
        return Ok(());
    }
    if let Some(rest) = input.strip_prefix("type ") {
        let parts: Vec<&str> = rest.splitn(2, ' ').collect();
        if parts.len() == 2 {
            sb.type_text(parts[0], parts[1]).await?;
            println!("Typed into {}", parts[0]);
        } else {
            println!("Usage: type <css> <text>");
        }
        return Ok(());
    }
    if let Some(rest) = input.strip_prefix("assert_text ") {
        let parts: Vec<&str> = rest.splitn(2, ' ').collect();
        if parts.len() == 2 {
            sb.assert_text(parts[0], parts[1]).await?;
            println!("Asserted text in {}", parts[0]);
        } else {
            println!("Usage: assert_text <css> <text>");
        }
        return Ok(());
    }
    if let Some(rest) = input.strip_prefix("save ") {
        let file = rest.trim();
        let script = sb.export_recording_as_rust()?;
        std::fs::write(file, script)?;
        println!("Saved recording to {}", file);
        return Ok(());
    }

    println!("Unknown command: {}", input);
    Ok(())
}
