#!/usr/bin/env python3
"""Render parity/api.toml and parity/upstream.toml into docs/parity.md.

Usage:
    python3 -I tools/parity/render_docs.py [--out PATH]
"""
import argparse
import collections
import pathlib
import tomllib

ROOT = pathlib.Path(__file__).resolve().parents[2]

SURFACES = [
    ("basecase", "BaseCase methods", "`BaseCase` (Python `BaseCase`)"),
    ("driver", "Driver methods", "Methods of Python's `Driver()`"),
    ("cdp", "CDP Mode methods", "Python `sb.cdp.*`; Rust holds the selector in a `Locator`"),
    ("cli", "Command-line commands", "`seleniumbase` / `sbase`"),
    ("options_pytest", "pytest options", "Python `--option` flags"),
    ("options_sb", "`SB()` arguments", "Keyword arguments of `SB()`"),
    ("options_driver", "`Driver()` arguments", "Keyword arguments of `Driver()`"),
    ("mcp_cdp", "MCP: CDP server", "`seleniumbase-mcp --server cdp`"),
    ("mcp_driver", "MCP: Driver server", "`seleniumbase-mcp --server driver`"),
    ("mcp_sb", "MCP: SB server", "`seleniumbase-mcp --server sb`"),
]
ORDER = ["implemented", "composed", "not-applicable", "planned"]


def cell(text):
    return (text or "").replace("|", "\\|").replace("\n", " ")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=pathlib.Path, default=ROOT / "docs/parity.md")
    out_path = parser.parse_args().out
    manifest = tomllib.loads((ROOT / "parity/api.toml").read_text(encoding="utf-8"))
    pinned = tomllib.loads((ROOT / "parity/upstream.toml").read_text(encoding="utf-8"))
    sb, mcp = pinned["seleniumbase"], pinned["seleniumbase_mcp"]

    out = [
        "# API parity with Python SeleniumBase",
        "",
        "<!-- Generated by tools/parity/render_docs.py from parity/api.toml. Do not edit. -->",
        "",
        f"This crate tracks SeleniumBase **{sb['version']}** (`{sb['commit'][:10]}`) and "
        f"seleniumbase-mcp (`{mcp['commit'][:10]}`), synced {pinned['sync']['date']}.",
        "",
        "| Status | Meaning |",
        "| --- | --- |",
        "| implemented | A Rust item with the same name exists. |",
        "| composed | Rust does it with a different item or a composition. |",
        "| not-applicable | Nothing to port; the reason is given. |",
        "| planned | Not done yet. |",
        "",
        "## Summary",
        "",
        "| Surface | Total | " + " | ".join(ORDER) + " |",
        "| --- | ---: | " + " | ".join("---:" for _ in ORDER) + " |",
    ]
    for key, title, _ in SURFACES:
        entries = manifest.get(key, {})
        counts = collections.Counter(e["status"] for e in entries.values())
        out.append(
            f"| [{title}](#{title.lower().replace(' ', '-').replace('`', '').replace(':', '')}) "
            f"| {len(entries)} | " + " | ".join(str(counts.get(s, 0)) for s in ORDER) + " |"
        )
    for key, title, blurb in SURFACES:
        entries = manifest.get(key, {})
        out += ["", f"## {title}", "", f"{blurb}.", "", "| Upstream | Status | Rust | Notes |", "| --- | --- | --- | --- |"]
        for name in sorted(entries):
            e = entries[name]
            notes = " ".join(x for x in (e.get("reason"), e.get("note"), e.get("divergence") and f"Differs: {e['divergence']}") if x)
            rust = f"`{e['rust']}`" if "rust" in e else ""
            out.append(f"| `{cell(name)}` | {e['status']} | {cell(rust)} | {cell(notes)} |")
    out.append("")
    out_path.write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
